### PR TITLE
Delta serler ui

### PR DESCRIPTION
**Pull request by shyamg91**
Merging the css additions and layout changes

### CODE REVIEW

**Comment by klauszhang** [comment]
Sorry buddy… I made some mess… 
the search boxes are under a deep reconstruction.. 
it is possible, you will have a lot of reconfiguration on the index page.
I am trying to add condition groups.. which will make this mess even complicated…

Please pull develop branch and check out the first hand stuff. (ps. I really should not merge the adv search stuff to develop branch before it is finished on delta-adv_search)
I believe it will finish before tomorrow noon.

Cheers,
Hao Zhang

**Comment by lpirl** [comment]
@shyamg91 is that the merge talked about or are you going to resolve the merge conflicts?

**Comment by shyamg91** [comment]
@lpirl yup this is the merge, i haven't started resolving them.

**Comment by shyamg91** [comment]
@klauszhang @lpirl so i checkout a new branch from develop ?

**Comment by klauszhang** [comment]
-..- you can if you want.. but remember to resolve the conflicts… lucky I will not touch the style stuff, there wont be a lot to resolve. 
but I think you will have some work on search index.

**Comment by shyamg91** [comment]
@klauszhang alright i will try resolving them. i suggest backing up your work elsewhere also . lol

**Comment by klauszhang** [comment]
that’s alright… I would recommend you: 
push your working branch to remote -> 
check out a local branch of develop and merge locally -> 
resolve the conflicts -> 
push local develop to remote.

if everything's good. then all codes will not be affected. if you think you mess up, just delete local folder and clone your remote branch and try again.

btw: NEVER use git push -f… well…just in case...

I pushed the most recent useable stuff on develop branch. I think probably I wont add anything else tonight. Have fun..

**Comment by shyamg91** [comment]
@klauszhang haha never -f ! 

Btw i kept your changes resolved it locally, and pushed it and tried to merge still the travis build failed.

**Comment by shyamg91** [comment]
@lpirl @klauszhang 
Failing scenarios
cucumber features/manage_columns.feature:12 # Scenario: Visible

cucumber features/manage_results.feature:12 # Scenario: Sort

cucumber features/manage_search_methods.feature:14 # Scenario: View

cucumber features/manage_shares.feature:12 # Scenario: Share

cucumber features/manage_views.feature:12 # Scenario: View

cucumber features/save_search.feature:14 # Scenario: Save and re-display search result

**Comment by klauszhang** [comment]
The problem is the user story. I changed some stuff on index which no longer exists. so.. you know the problem..
ci actually looking for “Search for: “ key word
I will figure this out...

**Comment by shyamg91** [comment]
@klauszhang alright. i merged successfully. Will talk to you tmrw to fully understand what advanced search is done and then i will restyle it

**Comment by klauszhang** [comment]
well, there is something wrong with the story:
Feature: Methods
 <>  As a registered user of SERLER
 <>  I want to be able to search for empirical evidence on different methods based on different constraints 
 <>  so that I can make informed decisions
 <>
 <>  Background:                                          # features/manage_search_methods.feature:6
 <>    Given I'm logged in as user                        # features/step_definitions/login_steps.rb:1
 <>      TODO
 <>    And I am on the search page                        # features/step_definitions/navigation_steps.rb:5
 <>    When I fill in "Search for:" with "saasbook"       # features/step_definitions/fill_in_steps.rb:1
 <>    And I select "Scrum" from methodolgy               # features/step_definitions/search_method_steps.rb:1
 <>      TODO (Cucumber::Pending)
 <>      ./features/step_definitions/search_method_steps.rb:2:in `/^I select "(.*?)" from methodolgy$/'
 <>      features/manage_search_methods.feature:10:in `And I select "Scrum" from methodolgy'
 <>    And I select "daily stand up meeting" from methods # features/step_definitions/search_method_steps.rb:6
 <>    And I click on "Search" button                     # features/step_definitions/click_steps.rb:13
 <>
 <>  Scenario: View                                             # features/manage_search_methods.feature:14
 <>    Then I should see results based on different constraints # features/step_definitions/content_check_steps.rb:25

I think it is somehow a little too big… I didn’t expect something so complex~ maybe I need ajax to read out stuff from database first.
anyway, i will contact Lukas to see what’s the issue.

good night.

**Comment by shyamg91** [comment]
@klauszhang Yea. Reading the story it does sound a little complex and nothing like what has been implemented.

**Pull request merged**
